name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # รันทุกวันตอนเที่ยงคืน UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add Upstream
        run: git remote add upstream https://github.com/makeplane/plane.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: |
          git checkout preview
          git merge upstream/preview --allow-unrelated-histories || true
          git push origin preview
