name: Sync Schedule by tag

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-latest-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add Upstream
      run: |
        git remote add upstream https://github.com/makeplane/plane.git
        git fetch upstream

    - name: Fetch latest upstream versions, then merge to 'master'
      id: sync
      run: |
        SYNC_VERSION="v$(curl --write-out '%{redirect_url}' 'https://github.com/makeplane/plane/releases/latest' | sed 's,.*/v,,')"
        echo "New version: $SYNC_VERSION"
        
        BRANCH_NAME="tag-$SYNC_VERSION"
        
        # Check if branch already exists
        if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
          echo "Branch $BRANCH_NAME already exists. Skipping PR creation."
          echo "BRANCH_CREATED=false" >> $GITHUB_ENV
          exit 0
        fi
        
        # Create new branch and merge changes
        git checkout -b "$BRANCH_NAME"
        git merge --allow-unrelated-histories upstream/preview || true
        
        if [ -n "$(git ls-files --unmerged)" ]; then
          echo "Resolving merge conflicts..."
          git checkout --theirs .
          git add .
          git commit -m "Resolved merge conflicts"
        fi
        
        git push origin "$BRANCH_NAME"
        echo "BRANCH_CREATED=true" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create Pull Request via GitHub API
      if: env.BRANCH_CREATED == 'true'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/pulls \
             -d '{
               "title": "🚀 Sync latest upstream changes: '${{ env.BRANCH_NAME }}'",
               "body": "This PR was automatically created to sync the latest upstream changes into the master branch.",
               "head": "'${{ env.BRANCH_NAME }}'",
               "base": "master"
             }'

